Resources:
  - Type: Counter
    Name: DdcpBuildNumber
    Alias: BuildNumberCounter
Pipelines:
  - Name: ddcp-build
    Notifications:
      Alias: Notifications
      Slack:
        - Channel: '#builds'
          UserName: buildbot
          Statuses:
            IN_PROGRESS:
              emoji: ':cold_sweat:'
            SUCCEEDED:
              emoji: ':aw_yeah:'
            FAILED:
              emoji: ':homer:'
            STOPPED:
              emoji: ':i_dunno:'
          WebHookUrl:
            '!Secret': SlackWebHookUrl
    Sources:
      - Name: Source
        Type: CodeCommit
        RepositoryName: ddcp
        BranchName: master
    Stages:
      - Name: BuildStage
        Actions:
          - Name: IncrementBuildNumber
            Type: Counter
            Alias: IncrementCounter
            Counter:
              '!Path':
                '!PathForAlias': BuildNumberCounter
            Operation: IncrementAndGet
            Order: 1
            OutputArtifactName: BuildNumber
          - Name: Build
            Type: CodeBuild
            Order: 2
            SourceName: Source
            InputArtifacts:
              - '!Path':
                  '!Join':
                    - '!PathForAlias': IncrementCounter
                    - - OutputArtifactName
            BuildSpec:
              Alias: BuildSpec
              Inline:
                version: 0.2
                env:
                  'secrets-manager':
                    NPM_TOKEN: 'NpmPublish:NPM_TOKEN'
                    GITHUB_USER: 'GithubPush:USERNAME'
                    GITHUB_TOKEN: 'GithubPush:TOKEN'
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                      ruby: 2.6
                      python: 3.7
                    commands:
                      - gem install cfn-nag
                      - pip install cfn-lint
                      - npm install
                      - npx lerna bootstrap
                      - npx lerna run build --scope @ddcp/tools
                  pre_build:
                    commands:
                      - '!Join':
                        - 'export BUILD_NUMBER=$(cat ${CODEBUILD_SRC_DIR_'
                        - '!Path':
                            '!Join':
                              - '!PathForAlias': IncrementCounter
                              - - OutputArtifactName
                        - '}/count)'
                      - export BUILD_VERSION="0.0.1-alpha.${BUILD_NUMBER}"
                      - echo ${BUILD_VERSION}
                  build:
                    commands:
                      - npx lerna run build
                      - npx lerna run lint
                      - npx lerna run pack
                      - npx lerna run artifact-lint
                  post_build:
                    commands:
                      - git clone https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/ddcp.git tmp
                      - cd tmp && git fetch && git reset --hard ${CODEBUILD_RESOLVED_SOURCE_VERSION} && cd ..
                      - mv tmp/.git .git
                      - rm -rf tmp
                      - git config user.email "ci@chelseau.com"
                      - git config user.name "DDCP CI"
                      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
                      - npx lerna publish ${BUILD_VERSION} --no-push --yes
                      - git push
                artifacts:
                  secondary-artifacts:
                    Manager:
                      files:
                        - packages/manager/dist/manager.yaml
                      discard-paths: yes
                    Synthesizer:
                      files:
                        - packages/synthesizer/dist/@ddcpsynthesizer.zip
                      discard-paths: yes
      - Name: PublishStage
        Actions:
          - Name: Manager
            Type: S3Publish
            Order: 1
            SourceName: Manager
            Extract: true
            BucketArn:
              '!Import': PublicBucketArn
            AccessControl: PublicRead
            CacheControl:
              - max-age: 86400
          - Name: Synthesizer
            Type: S3Publish
            Order: 1
            SourceName: Synthesizer
            Extract: true
            BucketArn:
              '!Import': PrivateBucketArn
  - Name: ddcp-branch-build
    GitHub:
      Auth:
        '!Secret': GitHubApp
      Defaults:
        Owner: curquhart
        Repo: ddcp
    Orchestrator: CloudWatch
    Notifications:
      '!Path':
        '!PathForAlias': Notifications
    Sources:
      - Name: Source
        Type: CodeCommit
        RepositoryName: ddcp
    Stages:
      - Name: BuildStage
        Actions:
          - Name: Build
            Type: CodeBuild
            Order: 1
            SourceName: Source
            BuildSpec:
              Inline:
                version:
                  '!Path':
                    '!Join':
                      - '!PathForAlias': BuildSpec
                      - - Inline
                        - version
                phases:
                  install:
                    '!Path':
                      '!Join':
                        - '!PathForAlias': BuildSpec
                        - - Inline
                          - phases
                          - install
                  pre_build:
                    commands:
                      - export BUILD_VERSION="0.0.0-development"
                  build:
                    '!Path':
                      '!Join':
                        - '!PathForAlias': BuildSpec
                        - - Inline
                          - phases
                          - build
