Pipelines:
  - Name: ddcp-build
    Sources:
      - Name: source
        Type: CodeCommit
        RepositoryName: ddcp
        BranchName: master
    Stages:
      - Name: BuildStage
        Actions:
          - Name: ManagerSynth
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                    commands:
                      - npm install
                  build:
                    commands:
                      - npm run synth-manager
          - Name: BuildS3Resolver
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                    commands:
                      - npm install
                  build:
                    commands:
                      - npm run build-s3resolver
          - Name: Build
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                    commands:
                      - npm install
                  build:
                    commands:
                      - npm run build
