Pipelines:
  - Name: ddcp-build
    Sources:
      - Name: source
        Type: CodeCommit
        RepositoryName: ddcp
        BranchName: master
    Stages:
      - Name: BuildStage
        Actions:
          - Name: ManagerSynth
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                      ruby: 2.6
                      python: 3.7
                    commands:
                      - gem install cfn-nag
                      - pip install cfn-lint
                      - npm install
                      - lerna bootstrap
                  build:
                    commands:
                      - lerna run build
                  post_build:
                    commands:
                      - lerna run cfn-lint
