Resources:
  - Type: Counter
    Name: DdcpBuildNumber
    '!Alias': BuildNumberCounter
  - Type: S3Bucket
    Name: DistCfnBucket
    '!Alias': DistCfnBucket
    RequesterPays: false
  - Type: S3Bucket
    Name: DistLambdasBucket
    '!Alias': DistLambdasBucket
    RequesterPays: true

Pipelines:
  - Name: ddcp-build
    EnableBadge: true
    Notifications:
      '!Alias': Notifications
      Slack:
        - Channel: '#builds'
          UserName: buildbot
          Statuses:
            IN_PROGRESS:
              emoji: ':cold_sweat:'
            SUCCEEDED:
              emoji: ':aw_yeah:'
            FAILED:
              emoji: ':homer:'
            STOPPED:
              emoji: ':i_dunno:'
          WebHookUrl:
            '!Secret': SlackWebHookUrl
    Sources:
      - Name: Source
        Type: Git
        Uri: git@github.com:curquhart/ddcp.git
        Auth:
          PrivateKey:
            '!Secret': GitHubMirrorPrivateKey
        Trigger: GitHubWebHook
        RepositoryName: ddcp
        BranchName: master
    Stages:
      - Name: BuildStage
        Actions:
          - Name: IncrementBuildNumber
            Type: Counter
            '!Alias': IncrementCounter
            Counter:
              '!Path':
                '!PathForAlias': BuildNumberCounter
            Operation: IncrementAndGet
            Order: 1
            OutputArtifactName: BuildNumber
          - Name: Build
            Type: CodeBuild
            Order: 2
            SourceName: Source
            InputArtifacts:
              - '!Path':
                  '!Join':
                    - '!PathForAlias': IncrementCounter
                    - - OutputArtifactName
            ComputeType: BUILD_GENERAL1_MEDIUM
            BuildSpec:
              '!Alias': BuildSpec
              Inline:
                version: 0.2
                env:
                  'secrets-manager':
                    NPM_TOKEN: 'NpmPublish:NPM_TOKEN'
                    GITHUB_USER: 'GithubPush:USERNAME'
                    GITHUB_PRIVATE_KEY: 'GitHubVersioningPrivateKey'
                phases:
                  install:
                    runtime-versions:
                      nodejs: 12
                      ruby: 2.6
                      python: 3.8
                    commands:
                      - gem install cfn-nag
                      - pip install cfn-lint
                      - npm install
                      - npx lerna bootstrap
                  pre_build:
                    commands:
                      - '!Script':
                          Bin: |
                            #!/usr/bin/env bash

                            set -e

                            eval $(ssh-agent -s)
                            echo "${GITHUB_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
                            mkdir -p ~/.ssh
                            chmod 0700 ~/.ssh
                            git clone git@github.com:${GITHUB_USER}/ddcp.git tmp
                            cd tmp && git fetch && git reset --hard ${CODEBUILD_RESOLVED_SOURCE_VERSION} && cd ..
                            mv tmp/.git .git
                            rm -rf tmp
                      - '!Join':
                        - 'export BUILD_NUMBER=$(cat ${CODEBUILD_SRC_DIR_'
                        - '!Path':
                            '!Join':
                              - '!PathForAlias': IncrementCounter
                              - - OutputArtifactName
                        - '}/count)'
                      - '!Join':
                          - 'export BUILD_VERSION=$('
                          - '!Script':
                              Bin: |
                                #!/usr/bin/env node

                                const fs = require('fs');

                                const bump = require(`${process.cwd()}/node_modules/standard-version/lib/lifecycles/bump`);

                                const startVersion = JSON.parse(fs.readFileSync('lerna.json').toString()).version;
                                const buildNumber = process.env.BUILD_NUMBER;
                                const [ startMajor, startMinor, startPatch ] = startVersion.split('.');

                                bump({
                                    infile: 'CHANGELOG.md',
                                    firstRelease: !fs.existsSync('CHANGELOG.md'),
                                    sign: false,
                                    noVerify: false,
                                    commitAll: false,
                                    silent: true,
                                    tagPrefix: 'v',
                                    scripts: {},
                                    skip: {},
                                    dryRun: true,
                                    gitTagFallback: true,
                                    preset: `${process.cwd()}/node_modules/conventional-changelog-conventionalcommits/index.js`,
                                    header: '# Changelog\n\nAll notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines.\n',
                                    types: [
                                        { type: 'feat', section: 'Features' },
                                        { type: 'fix', section: 'Bug Fixes' },
                                        { type: 'chore', hidden: true },
                                        { type: 'docs', hidden: true },
                                        { type: 'style', hidden: true },
                                        { type: 'refactor', hidden: true },
                                        { type: 'perf', hidden: true },
                                        { type: 'test', hidden: true }
                                    ],
                                    preMajor: Number(startMajor) < 1,
                                    commitUrlFormat: '{{host}}/{{owner}}/{{repository}}/commit/{{hash}}',
                                    compareUrlFormat: '{{host}}/{{owner}}/{{repository}}/compare/{{previousTag}}...{{currentTag}}',
                                    issueUrlFormat: '{{host}}/{{owner}}/{{repository}}/issues/{{id}}',
                                    userUrlFormat: '{{host}}/{{user}}',
                                    releaseCommitMessageFormat: 'chore(release): {{currentTag}}',
                                    issuePrefixes: [ '#' ],
                                    packageFiles: [ 'package.json' ],
                                    bumpFiles: [ 'package.json', 'package-lock.json' ]
                                }, startVersion.replace(/-.+$/, '')).then((endVersion) => {
                                    const [ endMajor, endMinor, endPatch ] = endVersion.split('.');

                                    if (startMajor === endMajor && startMinor === endMinor && startPatch.replace(/-.+$/, '') === endPatch.replace(/-.+$/, '')) {
                                        console.log(`${endMajor}.${endMinor}.${endPatch}-beta.${buildNumber}`)
                                    }
                                    else {
                                        console.log(`${endVersion}-${buildNumber}`)
                                    }
                                }).catch((err) => {
                                    console.error(err);
                                    process.exit(1);
                                });
                          - ')'
                      - echo ${BUILD_VERSION}
                  build:
                    commands:
                      - npx lerna run build
                      - npm t
                      - npx lerna run lint
                      - npx lerna run pack
                      - npx lerna run artifact-lint
                  post_build:
                    commands:
                      - '!Script':
                          Bin: |
                            #!/usr/bin/env bash

                            set -e

                            if [[ ${CODEBUILD_BUILD_SUCCEEDING} -eq 1 ]]
                            then
                              # is head tagged? if so, we're done.
                              if [[ "$(git tag --contains HEAD)" == "" ]]
                              then
                                git config user.email "ci@chelseau.com"
                                git config user.name "DDCP CI"
                                echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
                                npx lerna publish ${BUILD_VERSION} --conventional-commits --no-push --yes | tee /tmp/publish-results && grep -qv "lerna ERR\|WARN" < /tmp/publish-results

                                eval $(ssh-agent -s)
                                echo "${GITHUB_PRIVATE_KEY}" | tr -d '\r' | ssh-add -

                                # separate commands because we want our tag to push even if we've fallen behind master.
                                git push origin v${BUILD_VERSION}
                                git push origin master
                              fi
                            fi

                            # Versioned artifacts
                            mkdir -p dist/manager/${BUILD_VERSION}
                            cp packages/manager/dist/manager.yaml dist/manager/${BUILD_VERSION}
                            mkdir -p dist/lambdas/${BUILD_VERSION}
                            cp packages/*/dist/*.zip dist/lambdas/${BUILD_VERSION}
                artifacts:
                  secondary-artifacts:
                    Manager:
                      files:
                        - dist/manager/${BUILD_VERSION}/*
                      base-path: dist/manager/
                    Lambdas:
                      files:
                        - dist/lambdas/${BUILD_VERSION}/*
                      base-path: dist/lambdas/
                reports:
                  'test-results':
                    files:
                      - reports/junit.xml
                    discard-paths: yes
                    file-format: JunitXml
      - Name: PublishStage
        Actions:
          - Name: Manager
            Type: S3Publish
            Order: 1
            SourceName: Manager
            Extract: true
            BucketArn:
              '!Path':
                '!Join':
                  - '!PathForAlias': DistCfnBucket
                  - - Outputs
                    - BucketArn
            AccessControl: PublicRead
            CacheControl:
              - 'max-age: 86400'
          - Name: Lambdas
            Type: S3Publish
            Order: 1
            SourceName: Lambdas
            Extract: true
            BucketArn:
              '!Path':
                '!Join':
                  - '!PathForAlias': DistLambdasBucket
                  - - Outputs
                    - BucketArn
            AccessControl: PublicRead
  - Name: ddcp-branch-build
    GitHub:
      Auth:
        '!Secret': GitHubApp
      Defaults:
        Owner: curquhart
        Repo: ddcp
    Orchestrator: CloudWatch
    Notifications:
      '!Path':
        '!PathForAlias': Notifications
    Sources:
      - Name: Source
        Type: CodeCommit
        RepositoryName: ddcp
        BranchPattern: '^(?!master$)'
    Stages:
      - Name: BuildStage
        Actions:
          - Name: Build
            Type: CodeBuild
            Order: 1
            SourceName: Source
            ComputeType: BUILD_GENERAL1_MEDIUM
            BuildSpec:
              Inline:
                version:
                  '!Path':
                    '!Join':
                      - '!PathForAlias': BuildSpec
                      - - Inline
                        - version
                phases:
                  install:
                    '!Path':
                      '!Join':
                        - '!PathForAlias': BuildSpec
                        - - Inline
                          - phases
                          - install
                  pre_build:
                    commands:
                      - export BUILD_VERSION="0.0.0-development"
                  build:
                    '!Path':
                      '!Join':
                        - '!PathForAlias': BuildSpec
                        - - Inline
                          - phases
                          - build
                reports:
                  '!Path':
                    '!Join':
                      - '!PathForAlias': BuildSpec
                      - - Inline
                        - reports
