Pipelines:
  - Name: ddcp-build
    Sources:
      - Name: source
        Type: CodeCommit
        RepositoryName: ddcp
        BranchName: master
    Stages:
      - Name: BuildStage
        Actions:
          - Name: ManagerSynth
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                      ruby: 2.6
                      python: 3.7
                    commands:
                      - gem install cfn-nag
                      - pip install cfn-lint
                      - npm install
                  build:
                    commands:
                      - npm run synth-manager
                  post_build:
                    commands:
                      - cfn-lint -i W3005 -- dist/cfn/manager.yaml
                      - cfn_nag_scan --fail-on-warnings --input-path dist/cfn/manager.yaml
          - Name: BuildS3Resolver
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                    commands:
                      - npm install
                  build:
                    commands:
                      - npm run build-s3resolver
          - Name: Build
            Type: CodeBuild
            Order: 1
            SourceName: source
            BuildSpec:
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                    commands:
                      - npm install
                  build:
                    commands:
                      - npm run build
