Pipelines:
  - Name: ddcp-build
    Notifications:
      Slack:
        - Channel: '#builds'
          UserName: buildbot
          Statuses:
            IN_PROGRESS:
              emoji: ':cold_sweat:'
            SUCCEEDED:
              emoji: ':aw_yeah:'
            FAILED:
              emoji: ':homer:'
            STOPPED:
              emoji: ':i_dunno:'
          WebHookUrl:
            '!SsmString': SlackWebHookUrl
    Sources:
      - Name: Source
        Type: CodeCommit
        RepositoryName: ddcp
        BranchName: master
    Stages:
      - Name: BuildStage
        Actions:
          - Name: Build
            Type: CodeBuild
            Order: 1
            SourceName: Source
            BuildSpec:
              Alias: BuildSpec
              Inline:
                version: 0.2
                phases:
                  install:
                    runtime-versions:
                      nodejs: 10
                      ruby: 2.6
                      python: 3.7
                    commands:
                      - gem install cfn-nag
                      - pip install cfn-lint
                      - npm install
                      - npx lerna bootstrap
                      - npx lerna run build --scope @ddcp/tools
                  build:
                    commands:
                      - npx lerna-audit
                      - npx lerna run lint
                      - npx lerna run build
                      - npx lerna run pack
                      - npx lerna run artifact-lint
                artifacts:
                  secondary-artifacts:
                    Manager:
                      files:
                        - packages/manager/dist/manager.yaml
                      discard-paths: yes
                    Synthesizer:
                      files:
                        - packages/synthesizer/dist/@ddcpsynthesizer.zip
                      discard-paths: yes
      - Name: PublishStage
        Actions:
          - Name: Manager
            Type: S3Publish
            Order: 1
            SourceName: Manager
            Extract: true
            BucketArn:
              '!Import': PublicBucketArn
            AccessControl: PublicRead
            CacheControl:
              - max-age: 86400
          - Name: Synthesizer
            Type: S3Publish
            Order: 1
            SourceName: Synthesizer
            Extract: true
            BucketArn:
              '!Import': PrivateBucketArn
  - Name: ddcp-branch-build
    Orchestrator: CloudWatch
    Sources:
      - Name: Source
        Type: CodeCommit
        RepositoryName: ddcp
    Stages:
      - Name: BuildStage
        Actions:
          - Name: Build
            Type: CodeBuild
            Order: 1
            SourceName: Source
            BuildSpec:
              Inline:
                version:
                  '!Path':
                    '!Join':
                      - '!PathForAlias': BuildSpec
                      - - Inline
                        - version
                phases:
                  '!Path':
                    '!Join':
                      - '!PathForAlias': BuildSpec
                      - - Inline
                        - phases
